import { useMemo, useState } from "react";
import { Download, Images, Plus, ShieldAlert, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
import { parseVendorDescription } from "@/lib/descriptionFormatter";
import { buildProductPackagesZip, duplicateWarnings, hashFile, specificationConflictWarnings, visualHashFile, type ImageAssignment, type PackageImage, type ProductVariation } from "@/lib/productPackage";

const createVariation = (name = ""): ProductVariation => ({ id: crypto.randomUUID(), name, sku: "", sourceNotes: "" });
const ProductPackageBuilder = () => {
  const [title, setTitle] = useState(""); const [vendor, setVendor] = useState(""); const [sourceUrl, setSourceUrl] = useState("");
  const [vendorText, setVendorText] = useState("");
  const [variations, setVariations] = useState<ProductVariation[]>([createVariation("Black"), createVariation("White")]); const [images, setImages] = useState<PackageImage[]>([]); const [imageUrl, setImageUrl] = useState("");
  const warnings = useMemo(() => [...duplicateWarnings(images), ...specificationConflictWarnings(variations)], [images, variations]);
  const updateVariation = (id: string, patch: Partial<ProductVariation>) => setVariations((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item));
  const analyzeFiles = async (files: FileList | null) => {
    if (!files) return; const additions: PackageImage[] = [];
    for (const file of Array.from(files)) {
      let visualHash: string | undefined; try { visualHash = await visualHashFile(file); } catch { visualHash = undefined; }
      additions.push({ id: crypto.randomUUID(), name: file.name, file, assignment: "shared", exactHash: await hashFile(file), visualHash });
    } setImages((current) => [...current, ...additions]);
  };
  const addUrl = () => { const url = imageUrl.trim(); if (!url) return; setImages((current) => [...current, { id: crypto.randomUUID(), name: url.split("/").pop()?.split("?")[0] || "image", sourceUrl: url, assignment: "questionable" }]); setImageUrl(""); };
  const download = async () => {
    const blob = await buildProductPackagesZip({ title, vendor, sourceUrl, sections: { ...parseVendorDescription(vendorText), productTitle: title }, variations, images }, warnings);
    const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "product"}-packages.zip`; link.click(); URL.revokeObjectURL(link.href);
  };
  return <div className="container max-w-6xl space-y-7 py-8">
    <div><Badge variant="secondary">Product Package Builder v0.2</Badge><h1 className="mt-3 text-3xl font-bold">Build independent product packages</h1><p className="mt-2 text-muted-foreground">Create a separate Shopify-ready folder for every color, size, or other product version. Nothing is published automatically.</p></div>
    <Card><CardHeader><CardTitle>1. Product source</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><div><Label>Product title</Label><Input aria-label="Product title" value={title} onChange={(e) => setTitle(e.target.value)} /></div><div><Label>Vendor</Label><Input aria-label="Vendor" value={vendor} onChange={(e) => setVendor(e.target.value)} /></div><div><Label>Vendor page URL</Label><Input aria-label="Vendor page URL" value={sourceUrl} onChange={(e) => setSourceUrl(e.target.value)} /></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Product description source</CardTitle></CardHeader><CardContent><Label>Paste vendor text</Label><Textarea className="mt-1 min-h-[220px]" placeholder="Paste the vendor description and tabs. Unknown headings become suggested tabs in the Shopify HTML." value={vendorText} onChange={(e) => setVendorText(e.target.value)} /></CardContent></Card>
    <Card><CardHeader><CardTitle>2. Independent products</CardTitle></CardHeader><CardContent className="space-y-4">{variations.map((variation) => <div key={variation.id} className="grid gap-3 rounded-lg border p-4 md:grid-cols-[1fr_1fr_2fr_auto]"><Input aria-label="Product version" placeholder="Black, White, 10 x 12…" value={variation.name} onChange={(e) => updateVariation(variation.id, { name: e.target.value })}/><Input aria-label="SKU" placeholder="SKU" value={variation.sku} onChange={(e) => updateVariation(variation.id, { sku: e.target.value })}/><Textarea aria-label="Source notes" placeholder="Source notes and specifications (one Label: Value per line)" value={variation.sourceNotes} onChange={(e) => updateVariation(variation.id, { sourceNotes: e.target.value })}/><Button variant="ghost" size="icon" disabled={variations.length === 1} onClick={() => setVariations((items) => items.filter((item) => item.id !== variation.id))}><Trash2 className="h-4 w-4"/></Button></div>)}<Button variant="outline" onClick={() => setVariations((items) => [...items, createVariation()])}><Plus className="mr-2 h-4 w-4"/>Add product version</Button></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Images className="h-5 w-5"/>3. Images</CardTitle></CardHeader><CardContent className="space-y-4"><Input type="file" multiple accept="image/*" onChange={(e) => analyzeFiles(e.target.files)}/><div className="flex gap-2"><Input aria-label="Image URL" placeholder="Paste an image URL" value={imageUrl} onChange={(e) => setImageUrl(e.target.value)}/><Button variant="outline" onClick={addUrl}>Add URL</Button></div>{images.map((image) => <div key={image.id} className="grid items-center gap-2 rounded border p-3 md:grid-cols-[2fr_1fr_1fr_auto]"><span className="truncate text-sm">{image.name}</span><select className="h-10 rounded-md border bg-background px-3 text-sm" value={image.assignment} onChange={(e) => setImages((items) => items.map((item) => item.id === image.id ? { ...item, assignment: e.target.value as ImageAssignment } : item))}><option value="shared">Shared</option><option value="variation">Specific product</option><option value="questionable">Questionable / REVIEW</option><option value="excluded">Excluded</option></select>{image.assignment === "variation" ? <select className="h-10 rounded-md border bg-background px-3 text-sm" value={image.variationId || ""} onChange={(e) => setImages((items) => items.map((item) => item.id === image.id ? { ...item, variationId: e.target.value } : item))}><option value="">Choose product</option>{variations.map((v) => <option key={v.id} value={v.id}>{v.name || "Unnamed"}</option>)}</select> : <span/>}<Button variant="ghost" size="icon" onClick={() => setImages((items) => items.filter((item) => item.id !== image.id))}><Trash2 className="h-4 w-4"/></Button></div>)}</CardContent></Card>
    {warnings.length > 0 && <Card className="border-amber-400"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-amber-600"/>Review warnings</CardTitle></CardHeader><CardContent className="space-y-2">{warnings.map((warning, index) => <p key={index} className="rounded bg-amber-50 p-3 text-sm"><strong>{warning.label}</strong>: {warning.message}</p>)}</CardContent></Card>}
    <Button size="lg" disabled={!title.trim() || variations.some((item) => !item.name.trim())} onClick={download}><Download className="mr-2 h-4 w-4"/>Download separate product packages ZIP</Button>
  </div>;
};
export default ProductPackageBuilder;
